import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './styles/globals.css'
import Sidebar from '@/app/components/Sidebar/Sidebar'
import { userData } from '@/app/components/User/user.mock'
import React from 'react'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '600'] })

export const metadata: Metadata = {
  title: 'CRM dashboard customers',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
    <body className={poppins.className}>
    <main className='lg:flex min-h-lvh'>
      <Sidebar/>
      <div className='w-full lg:w-3/4 p-6 xl:py-[41px] xl:pl-[71px] xl:pr-[95px]'>
        <h2 className='text-2xl font-medium mb-6 lg:mb-[51px]'>
          Hello {userData.name} <span className='inline-block animate-wave'>&#x1F44B;&#x1F3FC;</span>,
        </h2>
        {children}
      </div>
    </main>
    </body>
    </html>
  )
}
